version: "3"

services:
  lilywhitebot:
    image: lilywhitebot
    restart: always
    working_dir: /home/node/app
    volumes:
      - lilywhitebot-plugins:/home/node/app/plugins
      - lilywhitebot-config:/home/node/app/config

volumes:
  lilywhitebot-plugins:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./plugins
  lilywhitebot-config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./config
