version: "3"

services:
  lilywhitebot:
    image: node:16
    restart: always
    working_dir: /home/node/app
    volumes:
      - lilywhitebot-plugins:/home/node/app/plugins
      - lilywhitebot-dir:/home/node/app
      - lilywhitebot-cache:/home/node/cache
    command: "npm run install-build-start"

  nginx:
    # ...
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # 與上面保持一致
      - lilywhitebot-cache:/var/www/html

volumes:
  lilywhitebot-plugins:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./plugins
  lilywhitebot-dir:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./
  lilywhitebot-cache:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./cache
