name: Build Test

on:
  push:
    branches:
      - master
      - develop
    tags:        
      - v**
  pull_request:
    branches:
      - master
  pull_request_review:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install dependencies
      run: npm install

    - name: Create temp config
      run: cp config/config.example.ts config/config.ts

    - name: Lint & Build
      run: |
        npm run lint
        npm run build

    - name: Get docker image tag
      run: echo "DOCKER_TAG=v$( cat package.json | jq .version -r )-$( git rev-parse --short=8 HEAD )" >> $GITHUB_ENV

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

      
    - name: Build
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        tags: |
          ghcr.io/sunafterrainwm/lilywhitebot:${{ env.DOCKER_TAG }}



