name: Docker Image Build - Tags

on:
  push:
    tags:
      - 'v**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Get docker image tag
        run: echo "DOCKER_TAG=v$( cat package.json | jq .version -r )-$( date -u +"%+4Y%m%d" )" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/sunafterrainwm/lilywhitebot:${{ env.DOCKER_TAG }}
            ghcr.io/sunafterrainwm/lilywhitebot:latest
